<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MuscleGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuscleGroupeRepository extends EntityRepository
{
}
